import React from 'react';
import CSSModules from 'react-css-modules';
import styles from './utils.css';

const logo = () => (<img className="logo" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFAAAABQCAYAAACOEfKtAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAFUSURBVHhe7dHBTcMwHEbx7NY9GIM1ugCTIHFmDbbgWGrpb2GV2Nh5auqo7yd9hxwsWy+LpBl9nk6XtPjUKANCBoQMCBkQMmCnHGp0cVwpxvf5PDQDFgwIHS5gunymP2hAyICQASEDQgaEpg2YQ40uju8m3bkWqbVd3jntw24YEDIgZEDIgJABIQNCBoQMCBkQMiBkQMiAkAEhA0IGDC9vr5e0+OxmwGDA6wxYMGA4yp814HWPCrhlcfx/swXM7xldHO82HKqGPGAtUmu9Ad+/PoZmwIIBGzt0wBxqdHH8j6cMuHZ5awYsGBAyIGRAyICQASEDQgaE7hFwy+J41dMErOkNVWNAA/7OgAUDQgaEDAhN+7AbBoQMCBkQSnduWRy/n3TJWqTWdnlYp91C1RgQMiBkQMiAkAGhowd8uPwHRxfHVWMoyICQASEDQgaEDCjNa1l+AB6LukV+fUN6AAAAAElFTkSuQmCC" />);

export default CSSModules(logo, styles);